# Generated by Django 5.0.3 on 2024-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndDeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.CharField(default='0/0', max_length=100)),
                ('mock_performance', models.CharField(default='0/0', max_length=100)),
                ('weekly_test', models.CharField(default='0/0', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MySQLDeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.CharField(default='0/0', max_length=100)),
                ('mock_performance', models.CharField(default='0/0', max_length=100)),
                ('weekly_test', models.CharField(default='0/0', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PythonDeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.CharField(default='0/0', max_length=100)),
                ('mock_performance', models.CharField(default='0/0', max_length=100)),
                ('weekly_test', models.CharField(default='0/0', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
